# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-04 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=64, verbose_name='place')),
                ('message', models.CharField(max_length=64)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
